DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
        "DEPARTMENT_ID" VARCHAR2 (50 CHAR) NOT NULL,
        "NAME" VARCHAR2 (50 CHAR) NOT NULL,
        "DESCRIPTION" VARCHAR2 (100 CHAR) NOT NULL,
        PRIMARY KEY ("DEPARTMENT_ID")
);

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
        "EMPLOYEE_ID" VARCHAR2 (50 CHAR) NOT NULL,
        "NAME" VARCHAR2 (50 CHAR) NOT NULL,
        "EMAIL_ID" VARCHAR2 (50 CHAR) NOT NULL,
        "DEPARTMENT_ID" VARCHAR2 (50 CHAR) NOT NULL,
        PRIMARY KEY ("EMPLOYEE_ID"),
        FOREIGN KEY("DEPARTMENT_ID") REFERENCES DEPARTMENT("DEPARTMENT_ID")
);

DROP TABLE IF EXISTS API_KEY;

CREATE TABLE API_KEY (
        "ID" BIGINT NOT NULL IDENTITY,
        "KEY" VARCHAR2 (50 CHAR) NOT NULL,
        PRIMARY KEY("ID")
)

